services:
  app_proxy:
    environment:
      APP_HOST: dashboard
      APP_PORT: 8080

  init_permissions:
    image: ghcr.io/rubel0278-bot/quantus-node:v1.0.2-Qm@sha256:b4b12e37beb9754e773e9e93ec892eeb895029c97f81f8213f005a791c715dcf
    restart: "no"
    user: "0:0"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    entrypoint: ["/bin/sh", "-c", "set -eu; mkdir -p /data; chown 10001:10001 /data; chmod ug+rwx /data"]

  node:
    image: ghcr.io/rubel0278-bot/quantus-node:v1.0.2-Qm@sha256:b4b12e37beb9754e773e9e93ec892eeb895029c97f81f8213f005a791c715dcf
    restart: unless-stopped
    depends_on:
      init_permissions:
        condition: service_completed_successfully
    user: "10001:10001"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - "30333:30333"
    security_opt:
      - no-new-privileges:true

  dashboard:
    image: ghcr.io/rubel0278-bot/quantus-node-dashboard:v1.0.0@sha256:efeb508653622d1d947a5f08c04cb2f0b6a75d03a8d0a0e5e0e30dea699060bc
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      NODE_RPC_URL: http://node:9944
      DATA_DIR: /data
    security_opt:
      - no-new-privileges:true
