services:
  app_proxy:
    environment:
      APP_HOST: node
      APP_PORT: 9944

  init_permissions:
    image: alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf254e9bea4045fa6c8c44de311d1
    restart: "no"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - /bin/sh
      - -ec
      - |-
        set -eu
        mkdir -p /data
        chown 10001:10001 /data
        chmod ug+rwx /data

  node:
    image: ghcr.io/rubel0278-bot/quantus-node:v1.0.2-Qm@sha256:b4b12e37beb9754e773e9e93ec892eeb895029c97f81f8213f005a791c715dcf
    restart: unless-stopped
    depends_on:
      init_permissions:
        condition: service_completed_successfully
    user: "10001:10001"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - "30333:30333"
    security_opt:
      - no-new-privileges:true
